POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Sin token tampoco funciona?",
    "author": "Tu vieja",
    "url": "http:tuvieja.com",
    "userId": "60786db9a67861101c72f782"
}

###
GET http://localhost:3003/api/blogs/

###
PUT http://localhost:3003/api/blogs/60770415ea98dfbd2fcd9586
Content-Type: application/json

{
    "likes": 30
}

###
PUT http://localhost:3003/api/blogs/60770415ea98dfbd2fcd9586
Content-Type: application/json

{
    "title": "Jarcorino las tarrias",
    "author": "El tarrias",
    "url": "http://lastarrias.com",
    "likes": 40
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "st",
    "name": "Alex Nogales",
    "password": "testing"
}

###
DELETE http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "anogales",
    "password": "password"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub2dhbGVzIiwiaWQiOiI2MDc4NmRiOWE2Nzg2MTEwMWM3MmY3ODIiLCJpYXQiOjE2MTg1MTEyNDR9.R54Zuo4motSHUNv8YqR2pKu81eR9PoSzNSyinysStpE

{
    "title": "Token testing maybe??",
    "author": "Tu vieja",
    "url": "http:tuvieja.com",
    "userId": "60786db9a67861101c72f782"
}